---
- hosts: linux

  tasks:
  - name: install nginx
    package:
      name:
        - nginx
      state: latest
    become: yes # noqa 403
  - name: copy index.html
    copy:
      src: index.html
      dest: /usr/share/nginx/html/index.html
    become: yes # noqa 403,208
  - name: start nginx service
    service:
      name: nginx
      state: started
    become: yes # noqa 403









